<?php

namespace vending_machineBundle\Repository;

/**
 * CanteenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanteenRepository extends \Doctrine\ORM\EntityRepository
{
}
