<?php

namespace vending_machineBundle\Repository;

/**
 * KindOfMachinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KindOfMachinesRepository extends \Doctrine\ORM\EntityRepository
{
}
