<?php

namespace vending_machineBundle\Repository;

/**
 * machineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class machineRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrderedByNumberOfSold()
    {
        $em = $this->getEntityManager();
        $products = $em->createQuery(
            'SELECT p FROM vending_machineBundle:machine p
            ORDER BY p.numberOfSold DESC
            ')
            ->setMaxResults(10)
            ->getResult();

        return $products;
    }
}
