<?php

namespace vending_machineBundle\Repository;

/**
 * machineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class machineRepository extends \Doctrine\ORM\EntityRepository
{
}
