<?php

namespace vending_machineBundle\Repository;

/**
 * MeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeatRepository extends \Doctrine\ORM\EntityRepository
{
}
