<?php

namespace vending_machineBundle\Repository;

/**
 * typesOfservicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typesOfservicesRepository extends \Doctrine\ORM\EntityRepository
{
}
