<?php

namespace vending_machineBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastRegisteredBadgeNr()
    {
        $em = $this->getEntityManager();
        $lastInsertedBadgeNr = $em->createQuery(
            'SELECT badge_nr p FROM vending_machineBundle:User p
            ORDER BY p.id DESC
            ')
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $lastInsertedBadgeNr;
    }
}