<?php

namespace vending_machineBundle\Repository;

/**
 * VeganRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeganRepository extends \Doctrine\ORM\EntityRepository
{
}
